/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComparatifAppCaloriesRouteImport } from './routes/comparatif-app-calories'
import { Route as AnalyseMasseGrasseIaRouteImport } from './routes/analyse-masse-grasse-ia'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparatifAppCaloriesRoute = ComparatifAppCaloriesRouteImport.update({
  id: '/comparatif-app-calories',
  path: '/comparatif-app-calories',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseMasseGrasseIaRoute = AnalyseMasseGrasseIaRouteImport.update({
  id: '/analyse-masse-grasse-ia',
  path: '/analyse-masse-grasse-ia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyse-masse-grasse-ia': typeof AnalyseMasseGrasseIaRoute
  '/comparatif-app-calories': typeof ComparatifAppCaloriesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyse-masse-grasse-ia': typeof AnalyseMasseGrasseIaRoute
  '/comparatif-app-calories': typeof ComparatifAppCaloriesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyse-masse-grasse-ia': typeof AnalyseMasseGrasseIaRoute
  '/comparatif-app-calories': typeof ComparatifAppCaloriesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyse-masse-grasse-ia'
    | '/comparatif-app-calories'
    | '/robots.txt'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyse-masse-grasse-ia'
    | '/comparatif-app-calories'
    | '/robots.txt'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/analyse-masse-grasse-ia'
    | '/comparatif-app-calories'
    | '/robots.txt'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyseMasseGrasseIaRoute: typeof AnalyseMasseGrasseIaRoute
  ComparatifAppCaloriesRoute: typeof ComparatifAppCaloriesRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparatif-app-calories': {
      id: '/comparatif-app-calories'
      path: '/comparatif-app-calories'
      fullPath: '/comparatif-app-calories'
      preLoaderRoute: typeof ComparatifAppCaloriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse-masse-grasse-ia': {
      id: '/analyse-masse-grasse-ia'
      path: '/analyse-masse-grasse-ia'
      fullPath: '/analyse-masse-grasse-ia'
      preLoaderRoute: typeof AnalyseMasseGrasseIaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyseMasseGrasseIaRoute: AnalyseMasseGrasseIaRoute,
  ComparatifAppCaloriesRoute: ComparatifAppCaloriesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
